#!/bin/sh
### BEGIN INIT INFO
# Provides:          rfkill_unblock_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Unblocks WiFi
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting rfkill_unblock_once"
    rfkill unblock all &&
    update-rc.d rfkill_unblock_once remove &&
    rm /etc/init.d/rfkill_unblock_once &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
