---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toe
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toe
  template:
    metadata:
      labels:
        app: toe
    spec:
      serviceAccountName: toe
      containers:
        - name: toe
          image: gcr.io/teknoir/toe:latest
          imagePullPolicy: Always
          env:
            - name: TOE_PROJECT
              value: "${GCP_PROJECT}"
            - name: TOE_IOT_REGISTRY
              value: "${IOT_REGISTRY}"
            - name: TOE_DEVICE
              value: "${DEVICE_ID}"
            - name: TOE_CA_CERT
              value: "/toe_conf/roots.pem"
            - name: TOE_PRIVATE_KEY
              value: "/toe_conf/rsa_private.pem"
          volumeMounts:
            - name: toe-volume
              mountPath: /toe_conf
      volumes:
        - name: toe-volume
          hostPath:
            # directory location on host
            path: /toe_conf
