---
apiVersion: v1
kind: Service
metadata:
  name: devstudio
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: devstudio
  ports:
    - name: web
      port: 1880
      targetPort: 1880
      protocol: TCP
      nodePort: 31880

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devstudio
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devstudio
  template:
    metadata:
      labels:
        app: devstudio
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: devstudio
          image: gcr.io/teknoir-poc/devstudio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1880
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /devstudio-data
            type: DirectoryOrCreate
